image: kluless/nats-streaming-kubernetes:v0.10.2
imagePullPolicy: Always 
replicas: 3

NatsCluster:
  ServiceUrl: nats
  ServicePort: 6222

NatsStreamingServer:
  ServicePort: 4222
  MonitoringPort: 8222
  VolumeSubPath: nats-streaming
          
Persistance:
  StorageClass: "kube-nfs"
  StorageSize: 2Gi
